#!/usr/bin/env python
import argparse
import os
from subprocess import call

lira_dir = os.environ['LIRA_DIR']

def setup(args):
	return None

def parse_args():
	parser = {}
	parser['argparse'] = argparse.ArgumentParser(description='LiRA: Linked read analysis to identify somatic single nucleotide variants in MDA amplified single cells.')
	parser['subparse'] = parser['argparse'].add_subparsers()
	parser['setup'] = parser['subparse'].add_parser('setup',help='Setup a new analysis.')
	parser['setup'].add_argument('-c','--config',default=None,help='path to a config file')
	parser['setup'].set_defaults(func=setup)
	parser['split_genome'] = parser['subparse'].add_parser('split_genome',help='Split the genome into runnable chunks, by chromosome. Job scripts are made in "ANALYSIS_PATH/job_scripts"')
	parser['split_genome'].add_argument('-c','--config',default=None,help='path to a config file')
	parser['split_genome'].add_argument('-m','--chr',default=None,help='chromosome')
	parser['split_genome'].set_defaults(func=split_genome)
	parser['get_vcf_info'] = parser['subparse'].add_parser('get_vcf_info',help='Extract LiRA-relevant info from the original VCF file.')
	parser['get_vcf_info'].add_argument('-c','--config',default=None,help='path to a config file')
	parser['get_vcf_info'].add_argument('-m','--chr',default=None,help='chromosome')
	parser['get_vcf_info'].set_defaults(func=get_vcf_info)
	parser['get_alt_counts'] = parser['subparse'].add_parser('get_alt_counts',help='Get alternate allele counts over all sites in a bulk sample.  Only necessary to run for bulk samples.')
	parser['get_alt_counts'].add_argument('-c','--config',default=None,help='path to a config file')
	parser['get_alt_counts'].add_argument('-m','--chr',default=None,help='chromosome')
	parser['get_alt_counts'].set_defaults(func=get_alt_counts)
	parser['collect_results'] = parser['subparse'].add_parser('collect_results',help='Collect results of job scripts made by "split_genome".  If not all jobs are complete, then this will print the jobs that are not done and exit.')
	parser['collect_results'].add_argument('-c','--config',default=None,help='path to a config file')
	parser['collect_results'].set_defaults(func=collect_results)
	return parser['argparse'].parse_args()

def setup(args):
	call(["Rscript","--vanilla",lira_dir + "/scripts/main.R",args.config,"setup"])

def split_genome(args):
	call(["Rscript","--vanilla",lira_dir + "/scripts/main.R",args.config,"split_genome",args.chr])

def get_vcf_info(args):
	call(["Rscript","--vanilla",lira_dir + "/scripts/main.R",args.config,"get_vcf_info",args.chr])

def get_alt_counts(args):
	call(["Rscript","--vanilla",lira_dir + "/scripts/main.R",args.config,"get_alt_counts",args.chr])

def collect_results(args):
	call(["Rscript","--vanilla",lira_dir + "/scripts/main.R",args.config,"collect_results"])
	
if __name__ == "__main__":
	args = parse_args()
	args.func(args)
